
web:
    build: .
    links:
        - db
    ports:
        - "80:80"
    volumes:
        - ./devis-factures:/devis-factures
db:
    image: mariadb:10.1
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: devis_factures
