
web:
    build: .
    links:
        - db
    ports:
        - "80:80"
    volumes:
        - ./devis-factures:/devis-factures
        - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
db:
    image: mariadb:10.1
    ports:
        - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: devis_factures
